server:
  # 服务端口
  port: 8080
spring:
  application:
    name: dubbo-nacos-provider
dubbo:
  application:
    qos-enable: false
    name: multi-registry-provider
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.huaweicloud.samples.service
  # 注册中心信息
  registries:
    registry1:
      address: ${DUBBO_REGISTRY_ADDRESS_1:nacos://127.0.0.1:8848}
    registry2:
      address: ${DUBBO_REGISTRY_ADDRESS_2:nacos://127.0.0.1:8848}
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 20880
